/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: glenatron (https://sketchfab.com/glenatron)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/94b24a60dc1b48248de50bf087c0f042
title: Littlest Tokyo
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/LittlestTokyo.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group
              position={[76.1, 163.9, 118.6]}
              rotation={[-Math.PI / 3, 0, 0]}
              scale={[3.1, 3.1, 3.1]}>
              <group position={[-97.4, -7.1, -96.3]}>
                <mesh
                  geometry={nodes.Object078_Plastic_Soft_0.geometry}
                  material={nodes.Object078_Plastic_Soft_0.material}
                />
              </group>
            </group>
            <group position={[41.1, -198.4, 208.7]} rotation={[-Math.PI / 2, 0, 0.9]}>
              <group position={[0, 1.3, 8]} rotation={[0, 0, 0]}>
                <group position={[0, -1.6, -6.2]}>
                  <mesh
                    geometry={nodes.leaf_normal_0.geometry}
                    material={nodes.leaf_normal_0.material}
                  />
                </group>
              </group>
              <group position={[2.1, -0.7, 5.1]} rotation={[0, Math.PI / 3, 0]}>
                <group position={[-2.1, 0.5, -3.2]}>
                  <mesh
                    geometry={nodes.hand2_normal_0.geometry}
                    material={nodes.hand2_normal_0.material}
                  />
                </group>
              </group>
              <group position={[-2.2, -0.7, 5.1]} rotation={[0, -Math.PI / 3, 0]}>
                <group position={[2.2, 0.5, -3.3]}>
                  <mesh
                    geometry={nodes.hand1_normal_0.geometry}
                    material={nodes.hand1_normal_0.material}
                  />
                </group>
              </group>
              <group position={[2.4, -0.9, 2]} rotation={[0, 0, 0]}>
                <group position={[-2.4, 0.7, -0.2]}>
                  <mesh
                    geometry={nodes.foot2_normal_0.geometry}
                    material={nodes.foot2_normal_0.material}
                  />
                </group>
              </group>
              <group position={[-2.5, -0.9, 2]} rotation={[0, 0, 0]}>
                <group position={[2.5, 0.7, -0.2]}>
                  <mesh
                    geometry={nodes.foot1_normal_0.geometry}
                    material={nodes.foot1_normal_0.material}
                  />
                </group>
              </group>
              <group position={[0, -0.3, 1.8]}>
                <mesh
                  geometry={nodes.body_normal_0.geometry}
                  material={nodes.body_normal_0.material}
                />
              </group>
            </group>
            <group
              position={[-54.4, 114.5, -87.6]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[3.1, 3.1, 3.1]}>
              <group position={[-55.3, -73.6, -80.3]}>
                <mesh
                  geometry={nodes.Object608_metalmat_0.geometry}
                  material={nodes.Object608_metalmat_0.material}
                />
                <mesh
                  geometry={nodes.Object608_paintmat_0.geometry}
                  material={nodes.Object608_paintmat_0.material}
                />
              </group>
            </group>
            <group position={[53.4, -91.1, 179.8]} rotation={[-1.5, 0, 0]}>
              <group position={[-138.5, 205.3, 96.5]}>
                <mesh
                  geometry={nodes.wire7_normal_0.geometry}
                  material={nodes.wire7_normal_0.material}
                />
              </group>
            </group>
            <group position={[85.5, -196.5, -246.4]} rotation={[-Math.PI / 2, 0, 3.1]}>
              <group position={[-12.9, 0, 8.4]} rotation={[0, 0, 0]}>
                <group position={[12.9, 0, 68.1]}>
                  <mesh
                    geometry={nodes.Object680_metalmat_0.geometry}
                    material={nodes.Object680_metalmat_0.material}
                  />
                </group>
              </group>
              <group position={[14.3, 0, 8.4]} rotation={[0, 0, 0]}>
                <group position={[12.9, 0, 68.1]}>
                  <mesh
                    geometry={nodes.Object681_metalmat_0.geometry}
                    material={nodes.Object681_metalmat_0.material}
                  />
                </group>
              </group>
              <group position={[0, 0, 76.4]}>
                <mesh
                  geometry={nodes.Object675_outline_0.geometry}
                  material={nodes.Object675_outline_0.material}
                />
                <mesh
                  geometry={nodes.Object675_metalmat_0.geometry}
                  material={nodes.Object675_metalmat_0.material}
                />
                <mesh
                  geometry={nodes.Object675_paintmat_0.geometry}
                  material={nodes.Object675_paintmat_0.material}
                />
                <mesh
                  geometry={nodes.Object675_glassmat_0.geometry}
                  material={nodes.Object675_glassmat_0.material}
                />
              </group>
            </group>
            <group
              position={[-29.3, -38.7, -7.8]}
              rotation={[-Math.PI / 2, 0, -0.7]}
              scale={[3.1, 3.1, 3.1]}>
              <group position={[-17.7, -77.4, -30.9]} rotation={[0, 0, 0.7]}>
                <mesh
                  geometry={nodes.Object532_normal_0.geometry}
                  material={nodes.Object532_normal_0.material}
                />
              </group>
            </group>
            <group position={[-245.5, -161.8, -259.3]} rotation={[-1.6, -0.1, -0.7]}>
              <group rotation={[0, 0, 0.7]}>
                <mesh
                  geometry={nodes.Object689_metalmat_0.geometry}
                  material={nodes.Object689_metalmat_0.material}
                />
              </group>
            </group>
            <group position={[-101.4, 184.6, -141.8]} rotation={[-Math.PI / 2, 0, -0.1]}>
              <group position={[-1, -3.6, -2.1]}>
                <mesh
                  geometry={nodes.Plane001_normal_0.geometry}
                  material={nodes.Plane001_normal_0.material}
                />
              </group>
            </group>
            <group
              position={[-95.3, 184.6, -141]}
              rotation={[Math.PI / 2, 0, 0.1]}
              scale={[-1, -1, -1]}>
              <group position={[-1, -3.6, -2.1]}>
                <mesh
                  geometry={nodes.Plane003_normal_0.geometry}
                  material={nodes.Plane003_normal_0.material}
                />
              </group>
            </group>
            <group position={[-83.2, 184.6, -140.4]} rotation={[-Math.PI / 2, 0, 0.3]}>
              <group position={[-1, -3.6, -2.1]}>
                <mesh
                  geometry={nodes.Plane104_normal_0.geometry}
                  material={nodes.Plane104_normal_0.material}
                />
              </group>
            </group>
            <group
              position={[-77.3, 184.6, -142.2]}
              rotation={[Math.PI / 2, 0, -0.3]}
              scale={[-1, -1, -1]}>
              <group position={[-1, -3.6, -2.1]}>
                <mesh
                  geometry={nodes.Plane103_normal_0.geometry}
                  material={nodes.Plane103_normal_0.material}
                />
              </group>
            </group>
            <group position={[133.5, 48.3, -68.3]} rotation={[-Math.PI / 2, 0, -1.9]}>
              <group position={[-1, -3.6, -2.1]}>
                <mesh
                  geometry={nodes.Plane105_normal_0.geometry}
                  material={nodes.Plane105_normal_0.material}
                />
              </group>
            </group>
            <group
              position={[131.5, 48.3, -62.4]}
              rotation={[Math.PI / 2, 0, 1.9]}
              scale={[-1, -1, -1]}>
              <group position={[-1, -3.6, -2.1]}>
                <mesh
                  geometry={nodes.Plane106_normal_0.geometry}
                  material={nodes.Plane106_normal_0.material}
                />
              </group>
            </group>
            <group position={[148.1, 111.7, 190.2]} rotation={[-Math.PI / 2, 0, 3]}>
              <group position={[-1, -3.6, -2.1]}>
                <mesh
                  geometry={nodes.Plane108_normal_0.geometry}
                  material={nodes.Plane108_normal_0.material}
                />
              </group>
            </group>
            <group
              position={[142, 111.7, 189.1]}
              rotation={[Math.PI / 2, 0, -3]}
              scale={[-1, -1, -1]}>
              <group position={[-1, -3.6, -2.1]}>
                <mesh
                  geometry={nodes.Plane107_normal_0.geometry}
                  material={nodes.Plane107_normal_0.material}
                />
              </group>
            </group>
            <group position={[172.1, 108.4, 188.6]} rotation={[-Math.PI / 2, 0, 2.1]}>
              <group position={[-1, -3.6, -2.1]}>
                <mesh
                  geometry={nodes.Plane109_normal_0.geometry}
                  material={nodes.Plane109_normal_0.material}
                />
              </group>
            </group>
            <group
              position={[169.2, 108.4, 183.1]}
              rotation={[Math.PI / 2, 0, -2.1]}
              scale={[-1, -1, -1]}>
              <group position={[-1, -3.6, -2.1]}>
                <mesh
                  geometry={nodes.Plane110_normal_0.geometry}
                  material={nodes.Plane110_normal_0.material}
                />
              </group>
            </group>
            <group position={[38.8, 198.6, 68.6]} rotation={[1.6, 0, -0.1]} scale={[-1, -1, -1]}>
              <group position={[-1, -3.6, -2.1]}>
                <mesh
                  geometry={nodes.Plane111_normal_0.geometry}
                  material={nodes.Plane111_normal_0.material}
                />
              </group>
            </group>
            <group position={[32.7, 198.6, 69.4]} rotation={[-Math.PI / 2, 0, 0.1]}>
              <group position={[-1, -3.6, -2.1]}>
                <mesh
                  geometry={nodes.Plane112_normal_0.geometry}
                  material={nodes.Plane112_normal_0.material}
                />
              </group>
            </group>
            <group position={[-134.9, -36.7, -123.6]} rotation={[-1.6, 0, 0]}>
              <group position={[49.8, -98.1, 42.1]}>
                <mesh
                  geometry={nodes.Object704_metalmat_0.geometry}
                  material={nodes.Object704_metalmat_0.material}
                />
                <mesh
                  geometry={nodes.Object704_Plastic_Soft_0.geometry}
                  material={nodes.Object704_Plastic_Soft_0.material}
                />
              </group>
            </group>
            <group position={[11.3, -53.6, -65.7]} rotation={[-1.7, -0.1, 0.1]}>
              <group position={[-101.1, -36.7, 53]} rotation={[0.2, 0, -0.1]}>
                <mesh
                  geometry={nodes.wire1_Plastic_Soft_0.geometry}
                  material={nodes.wire1_Plastic_Soft_0.material}
                />
              </group>
            </group>
            <group position={[51.8, -44, -45.5]} rotation={[-1.6, 0, -0.8]}>
              <group position={[3.7, -65.2, -24.5]} rotation={[0, 0, -2.9]} scale={[3.1, 3.1, 3.1]}>
                <group position={[-91.9, 2.9, -19.1]} rotation={[0, 0, -0.5]}>
                  <mesh
                    geometry={nodes.Object081_normal_0.geometry}
                    material={nodes.Object081_normal_0.material}
                  />
                </group>
              </group>
              <group
                position={[3.8, -102.2, -21.4]}
                rotation={[0.1, -0.1, -2.3]}
                scale={[3.1, 3.1, 3.1]}>
                <group position={[-78.7, -54.7, -19.1]}>
                  <mesh
                    geometry={nodes.Object332_normal_0.geometry}
                    material={nodes.Object332_normal_0.material}
                  />
                </group>
              </group>
              <group
                position={[0.5, -22.7, -18.8]}
                rotation={[0.1, 0, -1.6]}
                scale={[3.1, 3.1, 3.1]}>
                <group position={[-78.7, -54.7, -19.1]}>
                  <mesh
                    geometry={nodes.Object682_normal_0.geometry}
                    material={nodes.Object682_normal_0.material}
                  />
                </group>
              </group>
              <group position={[-80.7, -112.4, 49.4]} rotation={[0, 0, 0.8]}>
                <mesh
                  geometry={nodes.wire2_Plastic_Soft_0.geometry}
                  material={nodes.wire2_Plastic_Soft_0.material}
                />
              </group>
            </group>
            <group position={[-3.8, -84.4, -56.4]} rotation={[-Math.PI / 2, 0, 0.1]}>
              <group position={[-83.2, -25.3, 89.8]} rotation={[0, 0, -0.1]}>
                <mesh
                  geometry={nodes.wire3_normal_0.geometry}
                  material={nodes.wire3_normal_0.material}
                />
              </group>
            </group>
            <group position={[50.9, -99, -52.3]} rotation={[-1.6, 0.1, -0.2]}>
              <group position={[-129.7, -48.9, 104.4]} rotation={[0, 0, 0.2]}>
                <mesh
                  geometry={nodes.wire4_normal_0.geometry}
                  material={nodes.wire4_normal_0.material}
                />
              </group>
            </group>
            <group position={[77.7, -109.8, -59.7]} rotation={[-1.6, 0, 0.3]}>
              <group position={[-165.8, 12.8, 115.2]} rotation={[0, 0, -0.3]}>
                <mesh
                  geometry={nodes.wire5_normal_0.geometry}
                  material={nodes.wire5_normal_0.material}
                />
              </group>
            </group>
            <group position={[26.4, -164.5, 185.1]} rotation={[-Math.PI / 2, 0, 0]}>
              <group position={[-111.4, 210.5, 169.9]}>
                <mesh
                  geometry={nodes['Object706_Material_#5518_0'].geometry}
                  material={nodes['Object706_Material_#5518_0'].material}
                />
              </group>
            </group>
            <group position={[26.4, -163.1, 185.1]} rotation={[-Math.PI / 2, 0, 0]}>
              <group position={[-111.4, 210.5, 168.5]}>
                <mesh
                  geometry={nodes['Object707_Material_#5518_0'].geometry}
                  material={nodes['Object707_Material_#5518_0'].material}
                />
              </group>
            </group>
            <group position={[-121.5, 153.7, 54.2]} rotation={[-Math.PI / 2, 0, 0]}>
              <group position={[-111.4, 210.5, 169.9]}>
                <mesh
                  geometry={nodes['Object708_Material_#5518_0'].geometry}
                  material={nodes['Object708_Material_#5518_0'].material}
                />
              </group>
            </group>
            <group position={[-121.5, 155.1, 54.2]} rotation={[-Math.PI / 2, 0, 0]}>
              <group position={[-111.4, 210.5, 168.5]}>
                <mesh
                  geometry={nodes['Object709_Material_#5518_0'].geometry}
                  material={nodes['Object709_Material_#5518_0'].material}
                />
              </group>
            </group>
            <primitive object={nodes._rootJoint} />
            <group position={[-85, 5.4, -25.4]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes.Object649_interiors_0.geometry}
                material={materials.interiors}
              />
              <mesh
                geometry={nodes.Object649_alpha_glass_0.geometry}
                material={materials.alpha_glass}
              />
              <mesh
                geometry={nodes['Object649_Material_#5512_0'].geometry}
                material={materials.Material_5512}
              />
              <mesh
                geometry={nodes.Object649_glass_transp_0.geometry}
                material={materials.glass_transp}
              />
              <mesh geometry={nodes.Object649_alpha_0.geometry} material={materials.alpha} />
              <mesh
                geometry={nodes.Object649_normal_0.geometry}
                material={nodes.Object649_normal_0.material}
              />
              <mesh
                geometry={nodes.Object649_metalmat_0.geometry}
                material={nodes.Object649_metalmat_0.material}
              />
              <mesh
                geometry={nodes.Object649_paintmat_0.geometry}
                material={nodes.Object649_paintmat_0.material}
              />
              <mesh
                geometry={nodes.Object649_Plastic_Soft_0.geometry}
                material={nodes.Object649_Plastic_Soft_0.material}
              />
              <mesh
                geometry={nodes.Object649_glassmat_0.geometry}
                material={nodes.Object649_glassmat_0.material}
              />
              <mesh
                geometry={nodes['Object649_Material_#5511_0'].geometry}
                material={materials.Material_5511}
              />
            </group>
            <group position={[-85, 5.4, -25.4]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes.Object674_outline_0_1.geometry}
                material={nodes.Object674_outline_0_1.material}
              />
              <mesh
                geometry={nodes.Object674_outline_0.geometry}
                material={nodes.Object674_outline_0.material}
              />
            </group>
            <group
              position={[-29.7, -38.7, -8.2]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[3.1, 3.1, 3.1]}>
              <group position={[-63.3, -47.9, -30.9]}>
                <mesh
                  geometry={nodes.Object531_normal_0.geometry}
                  material={nodes.Object531_normal_0.material}
                />
              </group>
            </group>
            <group position={[-85, 5.4, -25.4]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes['Object705_Material_#5516_0'].geometry}
                material={materials.Material_5516}
              />
            </group>
            <group position={[-173.4, -142.5, 79.9]} rotation={[-Math.PI / 2, 0, 0]}>
              <group
                position={[80.2, -106, -3]}
                rotation={[-0.3, 0.9, -1.4]}
                scale={[0.8, 0.8, 0.8]}>
                <group position={[0.7, 4, 18]}>
                  <mesh
                    geometry={nodes.Object619_alpha_0.geometry}
                    material={nodes.Object619_alpha_0.material}
                  />
                </group>
              </group>
              <group
                position={[-62, -105.9, -1.4]}
                rotation={[-0.3, 0.9, -1.4]}
                scale={[0.8, 0.8, 0.8]}>
                <group position={[0.7, 4, 18]}>
                  <mesh
                    geometry={nodes.Object620_alpha_0.geometry}
                    material={nodes.Object620_alpha_0.material}
                  />
                </group>
              </group>
              <group
                position={[-81.1, 105.4, -0.7]}
                rotation={[-0.3, 0.9, -1.4]}
                scale={[0.8, 0.8, 0.8]}>
                <group position={[0.7, 4, 18]}>
                  <mesh
                    geometry={nodes.Object621_alpha_0.geometry}
                    material={nodes.Object621_alpha_0.material}
                  />
                </group>
              </group>
            </group>
            <group position={[-85, 5.4, -25.4]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes.Object622_alpha_0.geometry}
                material={nodes.Object622_alpha_0.material}
              />
            </group>
            <skinnedMesh
              geometry={nodes.Object224_normal_0.geometry}
              material={nodes.Object224_normal_0.material}
              skeleton={nodes.Object224_normal_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object688_normal_0.geometry}
              material={nodes.Object688_normal_0.material}
              skeleton={nodes.Object688_normal_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object687_normal_0.geometry}
              material={nodes.Object687_normal_0.material}
              skeleton={nodes.Object687_normal_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object697_normal_0.geometry}
              material={nodes.Object697_normal_0.material}
              skeleton={nodes.Object697_normal_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object698_normal_0.geometry}
              material={nodes.Object698_normal_0.material}
              skeleton={nodes.Object698_normal_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object699_normal_0.geometry}
              material={nodes.Object699_normal_0.material}
              skeleton={nodes.Object699_normal_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object700_normal_0.geometry}
              material={nodes.Object700_normal_0.material}
              skeleton={nodes.Object700_normal_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object224_metalmat_0.geometry}
              material={nodes.Object224_metalmat_0.material}
              skeleton={nodes.Object224_metalmat_0.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/LittlestTokyo.glb')
